### PR TITLE
CI: change managed runner to self-hosted runner

### PR DESCRIPTION
**Pull request by dharmendrakariya**
Changing managed runner to self-hosted runner!

### CODE REVIEW

**Comment by sanekto** [comment]
It has been queued for the last 4hs ...

**Comment by ph1t0** [comment]
There's no runner configured: https://github.com/KarpatkeyDAO/defi-protocols/settings/actions/runners

**Comment by dharmendrakariya** [comment]
> There's no runner configured: https://github.com/KarpatkeyDAO/defi-protocols/settings/actions/runners

on it!

**Comment by sanekto** [comment]
Great! Thanks! Just to mention that it took 4 minutes to run instead of 1.

**Pull request merged**
